server:
  port: 9096
  # htpasswd: "/etc/acmeproxy/htpasswd"
  accesslog: "/var/log/acmeproxy.log"

provider: "transip"

filter:
  ips:
    - "127.0.0.1"
    - "172.16.0.0/16"
  domains:
    - "example.com"

environment:
  TRANSIP_ACCOUNT_NAME: mdbraber
  TRANSIP_PRIVATE_KEY_PATH: /etc/acmeproxy/transip.key
  TRANSIP_POLLING_INTERVAL: 30
  TRANSIP_PROPAGATION_TIMEOUT: 600
